[package]
name = "bigtable-client"
description = "An async Rust client for Google Cloud Bigtable"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
figment.workspace = true
http.workspace = true
humantime-serde.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
figment = { workspace = true, features = ["test"] }

[lints]
workspace = true
